### ISSUE TITLE
Compile 2 SASS directories

### ISSUE THREAD

**Issue by EmmanuelDemey** [robfletcher/gradle-compass#10]
Hi, 

I have just found your plugin, and it works like a charm. 

Can we have compile 2 different SASS directories ? for example, I have a components/ and src/main/webapp/css directories. After the compilation, the generated CSS files will be placed in the original folder. 

Thanks

Manu

**Comment by RoelRoel** [comment]
I also would like to build Sass for multiple dirs. I use android productflavors. But I have no idea how where to start...

**Comment by junhopark** [comment]
Same as well.  Would be great to be able to build Sass for multiple directories.

**Comment by Gillespie59** [comment]
any news about this issue ?
