### ISSUE TITLE
Need jcenter in example

### ISSUE THREAD

**Issue by fsparv** [robfletcher/gradle-compass#44]
dependency reolution failed with 

    buildscript {
        repositories {
            mavenCentral()
            maven { url "http://dl.bintray.com/robfletcher/gradle-plugins" }
        }
        dependencies {
            classpath "com.github.robfletcher:compass-gradle-plugin:2.0.5"
        }
    }

It seems that gradle-processes is on jcenter not maven-central, so I succeeded with

    buildscript {
        repositories {
            mavenCentral()
            jcenter()
            maven { url "http://dl.bintray.com/robfletcher/gradle-plugins" }
        }
        dependencies {
            classpath "com.github.robfletcher:compass-gradle-plugin:2.0.5"
        }
    }

The front page should probably be updated to reflect this.

**Comment by robfletcher** [comment]
Fixed by PR
