### ISSUE TITLE
rb-inotify-0.9.6.gem not found

### ISSUE THREAD

**Issue by benweizhu** [robfletcher/gradle-compass#54]
hi,

rubygems:rb-inotify has been required to update to 0.9.6. 

But production.s3.rubygems.org doesn't have this yet, which caused below:

http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem

Artifact 'rb-inotify.gem (rubygems:rb-inotify:0.9.6)' not found.
     Searched in the following locations:
         http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem

Can someone help me?

**Comment by alfasapy** [comment]
Having the same issue here.

You can work around it temporarily, by forcing Gradle to use the old version.

`configurations.all {
        resolutionStrategy.force 'rubygems:rb-inotify:0.9.5'
}`

**Comment by benweizhu** [comment]
@alfasapy .Thanks a lot. This works for me.
